package multhreadfiletransport.test.file_transport.multi_receiver;

public enum EReceiveAction {
	DO_NOTHING,
	GET_FILE_LIST_INFO,
	BEGIN_RECEIVE_ONE_FILE,
	RECEIVING,
	END_RECEIVE_ONE_FILE,
	RECEIVE_FAILURE,
	RECEIVE_OVER,
	ONE_RECEIVER_FINISHED,
	NEW_RECEIVER,
	ADD_REQUEST_FILE,
	BEGIN_JOIN,
	GET_NEEDED_JOIN_COUNT,
	JOINED_ONE,
	END_JOIN,
	ALL_DONE,
	STOP_RECEIVE,
}
